# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
GMAIL_DOMAIN: gmail.com
GMAIL_USERNAME: sethtfo@gmail.com
GMAIL_PASSWORD: S3cr3ts
S3_BUCKET_NAME: sethmile
AWS_ACCESS_KEY_ID: AKIAIH3DCK2ALVBYV6PQ
AWS_SECRET_ACCESS_KEY: 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