# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da8801b0e28c06dd1f7df7d682285e65db98d1383e312e311595701824bc945d4688a51c34450101bee7f8d05605b570fb608bdfd76b0232d8e84c9f0ba8b8b0

test:
  secret_key_base: 639c680a4efa32878d82d80190848f6f0271f81b603ebee2c2503c04820ace9005b0937dd08c0f1f3a2352fe6c2eb63e5771ce7026b0c5296369a01972dc15d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
